<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NAutomate.Abstractions\NAutomate.Abstractions.csproj" />
    <ProjectReference Include="..\NAutomate.Modules.Shell\NAutomate.Modules.Shell.csproj" />
    <PackageReference Include="Appium.WebDriver" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
